version: '3.7'

services:
  caching:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  # back:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - caching
  #   environment:
  #     - REDIS_HOST=caching
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./index.js:/app/index.js
  #   links:
  #     - "caching:redis"

volumes:
  redis_data:
    driver: local
# version: '3.7'
# services:
#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     volumes: 
#       - cache:/data
# volumes:
#   cache:
#     driver: local
