version: '3.7'

services:
  caching:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - caching
      - grpc
    environment:
      - REDIS_URL=redis://caching
      - GRPC_URL=http://grpc
    ports:
      - "3000:3000"
    volumes:
      - ./index.js:/app/index.js
    links:
      - "caching:redis"
  db:
    container_name: db
    image: "postgres:latest"
    volumes:
      - ./dbb/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    expose:
      - '5432'
  grpc:
    container_name: grpc
    build: 
      context: ./grpc/grpc_server/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT= 5432
      - DB_USER=postgres
      - DB_PASSWORD=marihuana
      - DB_NAME=tiendita
    depends_on:
      - db
    

volumes:
  redis_data:
    driver: local
# version: '3.7'
# services:
#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     volumes: 
#       - cache:/data
# volumes:
#   cache:
#     driver: local
